export default {
  GET_SIDO_OPTIONS: "getSidoOptions",
  GET_GUGUN_OPTIONS: "getGugunOptions",
  GET_DONG_OPTIONS: "getDongOptions",
  GET_APT: "getApt",
  SET_SIDO_OPTIONS: "setSidoOptions",
  SET_GUGUN_OPTIONS: "setGugunOptions",
  SET_DONG_OPTIONS: "setDongOptions",
  SET_SIDO: "setSido",
  SET_GUGUN: "setGugun",
  SET_DONG: "setDong",
  SET_APT: "setApt",
  SET_MIN_AREA: "setMinArea",
  SET_MAX_AREA: "setMaxArea",
  SET_MIN_AMOUNT: "setMinAmount",
  SET_MAX_AMOUNT: "setMaxAmount",
};
