export default {
  GET_SIDO_OPTIONS: "getSidoOptions",
  GET_GUGUN_OPTIONS: "getGugunOptions",
  GET_DONG_OPTIONS: "getDongOptions",
  GET_HOUSE: "getHouse",
  GET_RENT_NOT_APT: "getRentNotApt",
  SET_SIDO_OPTIONS: "setSidoOptions",
  SET_GUGUN_OPTIONS: "setGugunOptions",
  SET_DONG_OPTIONS: "setDongOptions",
  SET_SIDO: "setSido",
  SET_GUGUN: "setGugun",
  SET_DONG: "setDong",
  SET_HOUSE: "setDealApt",
  SET_MIN_AREA: "setMinArea",
  SET_MAX_AREA: "setMaxArea",
  SET_MIN_AMOUNT: "setMinAmount",
  SET_MAX_AMOUNT: "setMaxAmount",
  SET_HOUSE_TYPE: "setHouseType",
  SET_APT_DEAL: "setAptDeal",
  SET_DEAL_TYPE: "setDealType",
};
